Repository autobrr/go-qbittorrent, pull requests merged in 2023-12, with the labels that each got.

#21 feat: SetPreferences
  methods.go
Labels: enhancement

#22 feat: add example usage
  examples/basic/main.go
Labels: documentation

#23 fix(AppPreferences): set ProxyType to type any
  domain.go
Labels: bug
